
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  S_VB_MEM=1000
  S_VB_CPUS=2

  W_VB_MEM=512
  W_VB_CPUS=1

  config.vm.synced_folder ".", "/shared"

  # Server VM - K3s Controller
  config.vm.define "nmaazouzS", primary: true do |server|
    server.vm.hostname = "nmaazouzS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = S_VB_MEM
      vb.cpus = S_VB_CPUS
    end
 
    server.vm.provision "shell", path: "scripts/server-setup.sh"
  end

  # Worker VM - K3s Agent
  config.vm.define "nmaazouzSW" do |worker|
    worker.vm.hostname = "nmaazouzSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = W_VB_MEM
      vb.cpus = W_VB_CPUS
    end

    worker.vm.provision "shell", path: "scripts/worker-setup.sh"
  end
end
